### ISSUE TITLE
Ability to query statsd metrics

### ISSUE THREAD

**Issue by dmyers** [thephpleague/statsd#22]
Is it possible or could it be added to be able to query statsd on metrics for say an app rather than just sending data which the readme has great examples for?

**Comment by marcqualie** [comment]
From what I remember (I haven't used StatsD in a while) it's more of a protocol for sending large amounts of data and aggregating that into another system, such as graphite.

Since the data is pipped elsewhere, and not stored in StatsD, it wouldn't be possible to query the StatsD instance for metrics. This would also be per StatsD implementation dependant as a none official statsd (which also doesn't support querying) servers can actually receive data via the protocol and do different things with it which is what I've done in the past.

**Comment by dmyers** [comment]
Yeah good point. I was just learning about StatsD and other metric systems recently and wasn't fully aware. Thanks for the explanation. I appreciate it. :+1:
