### ISSUE TITLE
When no network connection at all - (0) php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by richardbenson** [thephpleague/statsd#25]
This may sound like an odd requirement, but should laravel be unable to get to the outside world at all (e.g. incoming only connection in private AWS subnets) then a `ConnectionException` is generated from Client.php, line 297 with: 

    (0) php_network_getaddresses: getaddrinfo failed: Name or service not known

Now, generally all boxes will have access to the outside world, but some of our environments don't and I'd rather not code in a whole bunch of `if`s around every `Statsd::whatever` call.

Is there any way to get these exceptions to be ignored as well?  One of the principals of StatsD was that it would fail gracefully because metrics matter less than page loads.

Interestingly, the throw is wrapped in a `if ($this->throwConnectionExceptions)` but it's still throwing them anyway even though `statsd.throwConnectionExceptions` is set to false.

Thanks in advance for any suggestions.

**Comment by marcqualie** [comment]
@richardbenson although your use case isn't very common, it is indeed a bug in this library. There was a test to cover this functionality, but only if the connection to the host was dropped, not if the DNS loookup itself failed.

I haven't written PHP in a few years, so this may not be the most elegant solution, but I was able to replicate your edge case and write the fix with the following commit: https://github.com/thephpleague/statsd/commit/0f095a7ccd5af415cec8b359757021458fd4d975

By doing the hostname lookup at the OS level rather than via the PHP C library socket connection, the error code sent back can be caught and ignored like the other connection errors using the configuration flag.

If you can confirm this fixes your issue I'll tag a new patch release for this.

**Comment by richardbenson** [comment]
Hi @marcqualie, thanks for the quick response but the issue seems to be not that an exception is generated by `fsockopen`, but that Client.php is assuming `throwConnectionExceptions` is set to true, furthermore the `trigger_error` call stops execution even if tCE is false.

I'm not explaining myself well I think, I'll chuck together a PR if I can trace it down and make it fall over gracefully.

**Comment by marcqualie** [comment]
This was resolved on dev-master a while ago but is now part of a tagged release:

https://github.com/thephpleague/statsd/releases/tag/1.4.0
